orb-attest/debian/orb-token.worldcoin-token.service

Fixup for commit `58d3f4a1c0f32605c3af3232877956dc9b447c4c`

fix: orb-attest executable name in .service

---

orb-slot-ctrl/debpkg/DEBIAN/postinst

This is currently breaking `orb-core`, since the `CURRENT_BOOT_SLOT` environment variable `orb-core` requires is not being set:
`/usr/local/lib/systemd/system-environment-generators/10-boot-slot.sh`:
```
echo "CURRENT_BOOT_SLOT=$(/usr/bin/get-slot)"
```

slot-ctrl: fix binary name in postinst

---

orb-slot-ctrl/README.md
orb-slot-ctrl/debpkg/DEBIAN/postinst
orb-slot-ctrl/debpkg/DEBIAN/prerm
orb-slot-ctrl/src/main.rs

get-slot is just a symlink to `orb-slot-ctrl`. The binary does introspection on its own name to determine its behavior. I don't see any reason for that complexity, so I'm removing this. It also simplifies the deb packaging for `orb-slot-ctrl`.

Remove get-slot symlink

---

orb-attest/Cargo.toml
orb-attest/src/config.rs
scripts/build_rust_artifacts.py

The flavors are problematic because they double compile times and cause us to have to produce and distribute prod and stage versions of every binary. However, most of the binaries are actually identical between these two versions.
Instead of doing compile time feature flags, we should simply detect this stuff with environment variables at runtime. In the absence of an env var, the code should fall back to prod behavior.
As a consequence, this also removes the `_prod_` part of the artifact names.

attest: remove flavors

---

orb-ui/src/engine/diamond.rs
orb-ui/src/engine/mod.rs
orb-ui/src/engine/pearl.rs

This PR adds a new UI event to handle magic-qr-codes `MagicQrActionCompleted { success: bool }`. 
It also moves the `QrLoadSuccess` sound from `QrScanCompleted` event to `QrScanSuccess` event. 
Goes with: https://github.com/worldcoin/priv-orb-core/pull/1143

orb-ui: Handle Magic QR Code Event

---

orb-ui/src/engine/diamond.rs
orb-ui/src/engine/mod.rs
orb-ui/src/engine/pearl.rs

This PR adds a new orb-ui Event, `QrScanTimeout`. 
The behavior is the same as `QrScanFail` with the addition of the `voice::Timeout`, both for Pearl and Diamond.
Goes with https://github.com/worldcoin/priv-orb-core/pull/1144

orb-ui: QrScanTimeout Event

---

orb-ui/examples/ui-replay.rs
orb-ui/src/dbus.rs
orb-ui/src/engine/diamond.rs
orb-ui/src/engine/pearl.rs

tested with UI events below, to be used with the `ui-replay` binary.
```
Apr 16 15:39:31 localhost worldcoin-ui[17338]: 2024-04-16T15:39:31.442272Z  INFO orb_ui::engine::pearl: UI event: {"SoundVolume":{"level":40}}
Apr 16 15:39:31 localhost worldcoin-ui[17338]: 2024-04-16T15:39:31.443722Z  INFO orb_ui::engine::pearl: UI event: {"SoundLanguage":{"lang":"en-US"}}
Apr 16 15:39:31 localhost worldcoin-ui[17338]: 2024-04-16T15:39:31.706397Z  INFO orb_ui::engine::pearl: UI event: {"QrScanTimeout":{"schema": "Operator"}}
Apr 16 15:39:31 localhost worldcoin-ui[17338]: 2024-04-16T15:39:31.813578Z  INFO orb_ui::engine::pearl: UI event: {"SoundVolume":{"level":40}}
Apr 16 15:39:31 localhost worldcoin-ui[17338]: 2024-04-16T15:39:31.814760Z  INFO orb_ui::engine::pearl: UI event: …
```

orb-ui: Dynamically change language

---

orb-ui/src/engine/pearl.rs

Behavior before:
1.  The LED ring progressed approx 90% and stayed there even though the signup was finished.
2. The LED ring was not cleared after the signup. 
3. The operator LEDs were not yellow after the failed signup
This PR solves all the above problems.

ui: Fix Event::SoftwareVersionBlocked

---

mcu-util/src/orb/main_board.rs

make it optional
still unused anyway

mcu-util: serial can only be obtained if orb-ui not running

---

mcu-util/src/main.rs
mcu-util/src/orb/main_board.rs
mcu-util/src/orb/security_board.rs

mcu-util: better errors and printing

---

.github/workflows/release.yaml
.github/workflows/rust-ci.yaml
CONTRIBUTING.md
Cargo.lock
mcu-util/Cargo.toml
mcu-util/README.md

Trying to keep our software consistently named. All crates should start with `orb-`.
This also allows us to begin creates releases for the `orb-mcu-util` component.

mcu-util: rename to orb-mcu-util and add to CI release options

---

orb-ui/src/engine/operator/connection.rs

so that it doesn't look too weird, and it doesn't show 'something' as not working.
before this PR, if internet connection was missing, all the 3 last LED would turn off.
cc @dangirsh @matthewpaul 
fixes  O-2652

orb-ui: in idle, turn on unused LEDs

---

Cargo.lock
Cargo.toml
artificer/Cargo.toml
mcu-util/Cargo.toml
orb-attest/Cargo.toml
orb-backend-state/Cargo.toml
orb-ui/Cargo.toml
orb-ui/sound/Cargo.toml

Currently, CI only builds with `--all` and doesn't go build individual crates. This means that cargo features are [unified across the workspace](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification).
There are two footguns with this:
* Building a crate directly with -p may reduce the set of features in use to exactly what is in that crate`s cargo.toml. This can break the build if we forgot to specify all the needed features, and we don't check that in CI.
* Changing the features on a crate likely causes the crate to need to be rebuilt. This means that all dependent crates also need to be rebuilt.
To improve both those footguns, it makes sense to just specify features on common crates directly in the workspace.

cargo: centralize features into workspace

---

Cargo.lock
artificer/Cargo.toml
artificer/build.rs
artificer/src/main.rs
build-info/Cargo.toml
build-info/build.rs
build-info/helper/Cargo.toml
build-info/helper/src/lib.rs
build-info/src/lib.rs
orb-backend-state/Cargo.toml
orb-backend-state/build.rs
orb-backend-state/src/main.rs
orb-slot-ctrl/Cargo.toml
orb-slot-ctrl/build.rs
orb-slot-ctrl/src/main.rs
orb-thermal-cam-ctrl/Cargo.toml
orb-thermal-cam-ctrl/build.rs
orb-thermal-cam-ctrl/src/main.rs
verity-tree-calc/Cargo.toml
verity-tree-calc/build.rs
verity-tree-calc/src/main.rs

* fixes a bug in build-info that caused it to always rebuild.
* makes orb-slot-ctrl use build-info.
* renames the crate to orb-build-info

build-info: add orb prefix and improve caching

---

security-utils/Cargo.toml

Orb-core doesn't support workspace inheritance unfortunately, which caused the other PR that uses security utils to break. This removes workspace inheritance for this crate.

security-utils: remove workspace inheritance

---

.github/workflows/rust-ci.yaml
scripts/build_rust_artifacts.py

Lets us stop having to manually write out the list of binaries. Also will allow us to reuse this workflow in orb-internal, since it is no longer specific to this repo.
Also seeking opinions: Would it be better for me to keep the json parsing in jq, or do you want me to port it to native python?

ci: autodetect cargo deb crates

---

.github/workflows/rust-ci.yaml
can/Cargo.toml
mcu-util/Cargo.toml
orb-thermal-cam-ctrl/Cargo.toml
orb-ui/Cargo.toml
orb-ui/sound/Cargo.toml
scripts/get_excludes.py
seek-camera/sys/Cargo.toml
seek-camera/wrapper/Cargo.toml

In order to reuse rust-ci.yaml, we need to automatically exclude crates that don't work on various platforms, without manually specifying them in CI.
To do this, I first introduced a custom metadata section for first party crates under [package.metadata.orb]. This can be used going forward as a place to put custom metadata for our crates that cargo subcommands and CI can inspect.
Next, I added a custom field under it called `unsupported_targets`, which lists out any of the target triples that CI runs that the crate is known to be incompatible with. 
Finally, I created a script to parse this data with jq and then call it in CI to get the crate exclusions for the current host architecture.

ci: generalize MAC_EXCLUDE

---

.github/workflows/python-ci.yaml
.github/workflows/release.yaml

Previously when we invoked rust-ci as a reusable workflow, the secrets weren't getting passed. This also adds a workflow_call to the python-ci.

ci: pass secrets to workflow_call

---

.github/workflows/release.yaml
.github/workflows/rust-ci.yaml

Should improve the speed of uploads. Uploads [previously](https://github.com/worldcoin/orb-software/actions/runs/9200402209/job/25306910455) took about 2 minutes. [Now](https://github.com/worldcoin/orb-software/actions/runs/9200624915/job/25307494731) they take 18 seconds.

ci: update artifacts actions to v4

---

.github/workflows/rust-ci.yaml
flake.lock
flake.nix

one thing to note: this will change the versions of any dynamically linked deps. But It should not matter for this repo AFAICT.
I've also keyed the rust cache on the flake.{nix,lock}. Because I found that the cache was stale. Note: If we used nix build in CI (which I was originally opposed to), this would have been a non-issue.

nix: switch to nixpkgs-23.11

---

orb-attest/src/remote_api.rs

chore: rename mcu-util->orb-mcu-util

---

Cargo.lock
mcu-interface/Cargo.toml
mcu-interface/examples/log_messages.rs

This adds an example of how to use `orb-mcu-interface`.
It also serves as a way to demonstrate that the current implementation is bugged - terminating `main` does not terminate the can_rx blocking task.

mcu-interface: add example

---

orb-attest/src/remote_api.rs

more secure to prevent remote code execution

orb-attest: full path to orb-mcu-util

---

mcu-interface/Cargo.toml
mcu-interface/examples/log_messages.rs
mcu-interface/src/can/canfd.rs
mcu-interface/src/can/isotp.rs
mcu-interface/src/can/mod.rs
mcu-interface/src/lib.rs
mcu-util/src/orb/main_board.rs
mcu-util/src/orb/security_board.rs

Changes in this PR:
* Turns the std::sync::mpsc channels into tokio channels. This allows us to receive messages asynchronously and reduces the number of spots we need to call blocking code from async.
* Refactors how the ack ids are created. I suspect previously there were some edge cases that could cause bugs, this new way is simpler and probably more correct.
* Adds a oneshot "kill" channel to inform `can_rx` that it should terminate.
* Places a few remaining spots that were blocking in async code behind a `tokio::task::spawn_blocking`.

mcu-interface: fix blocking, add kill for can_rx task, fix ack

---

hil/src/download_s3.rs

I always forget how to log in with the aws cli. This adds some helpful text to give the right command.

hil: add hint for login to sso

---

mcu-util/src/orb/main_board.rs
mcu-util/src/orb/security_board.rs

when fetching data, don't fail
but prefer unfilled struct
@TheButlah i'd like your thought on this kind of construct. I think it's fine not to fail when fetching the data so that we can at least print the pieces of info that were fetched.

orb-mcu-util: don't fail on build

---

Cargo.lock
mcu-interface/Cargo.toml
mcu-interface/examples/log_messages.rs
mcu-interface/src/can/canfd.rs
mcu-interface/src/can/isotp.rs
mcu-interface/src/can/mod.rs
mcu-util/Cargo.toml
mcu-util/src/main.rs
mcu-util/src/orb/main_board.rs
mcu-util/src/orb/mod.rs
mcu-util/src/orb/security_board.rs

This PR adds explicit task handles for `can_rx`, and also propagates them up through all of the callers. It also does a bit of refactoring to mcu-util's board info logic to make it slightly more correct and easier to read.
The reason this change is needed is so that panics or other errors inside the can_rx task can be observed by the rest of the program. Otherwise, the task could silently die but the process itself and the other threads would continue happily along.

mcu-util: explicitly join on task handles

---

orb-qr-link/src/user_data.rs
orb-qr-link/tests/verification.rs

This PR is a part of the new PCP v3 spec:
https://www.notion.so/worldcoin/Personal-Data-Custody-Package-Versions-4d70da1201bc4d2da200769968c5b275?d=4a2afb31339745c8be05b1d2582f24f4#ee7d1958b23641028905ce2cda9d4a0c

orb-qr-link: Add pcp_version field to UserData

---

Cargo.lock
Cargo.toml
const-concat/Cargo.toml
const-concat/README.md
const-concat/src/lib.rs
orb-attest/Cargo.toml
orb-attest/src/client.rs

I didn't like that the const_format crate is so incredibly complex. There is a lot of unsafe and also a lot of cursed code in it.
I would much rather use a solution that covers the 80% use case of concatenating strings with 0 unsafe, minimal LOC, and less SBOM risk.

orb-const-concat: initial commit

---

mcu-util/src/orb/dfu.rs

to reset dfu state on mcu side and make sure flash is erased before writing

orb-mcu-util: block count must start at 0 

---

Cargo.lock
artificer/src/main.rs
build-info/Cargo.toml
build-info/src/lib.rs
hil/src/main.rs
mcu-util/Cargo.toml
mcu-util/build.rs
mcu-util/src/main.rs
orb-attest/Cargo.toml
orb-attest/build.rs
orb-attest/src/client.rs
orb-attest/src/lib.rs
orb-backend-state/src/main.rs
orb-slot-ctrl/src/main.rs
orb-thermal-cam-ctrl/src/main.rs
orb-ui/Cargo.toml
orb-ui/build.rs
orb-ui/src/main.rs
verity-tree-calc/src/main.rs

I noticed that not all binaries were including the git sha in the build information. I've added the necessary functionality to the orb_build_info crate and updated all the binaries to use it.
I also bumped the version number for orb-mcu-util.

binaries: improve version reporting

---

mcu-util/src/orb/main_board.rs
mcu-util/src/orb/security_board.rs

heartbeat is sent, when initializing orb-mcu-util, to check that microcontrollers are alive
but if it's not, don't fail because the orb-mcu-util command (ie reboot, update..) might be targeted to the other, responsive, MCU
```
(venv) (os-9828b07) worldcoin@id-eff7c442:/mnt/scratch$ ./orb-mcu-util info
2024-06-14T08:04:41.249445Z ERROR orb_mcu_util::orb::security_board: Failed to send heartbeat to security mcu: Error {
msg: "ack not received (raw)",
source: Elapsed(
(),
),
}
```

orb-mcu-util: don't fail on building boards object

---

mcu-util/src/orb/main_board.rs

orb-ui should be the only user, otherwise it's not possible to use orb-ui with orb-mcu-util at the same time

orb-mcu-util: remove usage of serial

---

orb-attest/src/lib.rs

- `color_eyre::install` was being called both in `crate::main` and in `crate::orb_attest::main` causing the application to crash

attest: remove double call to color_eyre::install

---

scripts/rust_ci_helper.py

One reason why I didn't have CI create releases by detecting when the version in the cargo.toml gets changed, is because I couldn't guarantee that the lockfile was up to date with the toml file.
This PR fixes that, and also should prevent us from ever again accidentally committing a version bump change without the associated Cargo.lock change.

ci: ensure lockfile is up to date

---

orb-supervisor/Cargo.toml
orb-supervisor/debian/orb-supervisor.worldcoin-supervisor.service

As part of merging orb-supervisor into orb-software, we need to make it's .deb file include the service file. Previously this lived in orb-os, but to be consistent with the way we do other stuff, I believe it should be moved into orb-software.
There is an associated PR at worldcoin/orb-os#478

supervisor: added .service file

---

Cargo.lock
Cargo.toml
build-info/README.md
orb-attest/Cargo.toml
orb-supervisor/CHANGELOG.md
orb-supervisor/Cargo.toml
orb-supervisor/build.rs
orb-supervisor/src/lib.rs
orb-supervisor/src/main.rs

Added a clap CLI so that we can call it with `--version` and get the build info. I also added build info into the binary.

supervisor: add version reporting

---

orb-attest/Cargo.toml
orb-attest/debian/orb-attest.worldcoin-attest.service

We decided [in slack](https://tfh.slack.com/archives/C052G91M2Q6/p1723142104085079?thread_ts=1723140011.732869&cid=C052G91M2Q6) that first-party code will live in /usr/local/bin from now on.

attest: move to /usr/local/bin

---

build-info/helper/src/lib.rs
build-info/src/lib.rs
orb-attest/src/lib.rs

Previously, git describe would sometimes show the revision and sometimes show the tag.
Now, we always ensure that we only show the revision, and do our own dirty detection.

build-info: add dirty and revision detect

---

Cargo.lock
orb-ui/Cargo.toml

Since we added the .wav files into the .deb, we should bump the version number.

ui: bump version

---

scripts/tsh-certs.sh
scripts/upload-certs.sh

* Downloads the provisioning material from an orb, given teleport access.
* Uploads the provisioning material back to the database.
- Re-provisioning a jetson with a different secure-element is not possible atm
- Uploading the attestation certificate is not necessary during re-provisioning

utils: automate remote provisioning

---

Cargo.lock
Cargo.toml
orb-supervisor/Cargo.toml
orb-supervisor/src/interfaces/manager.rs
orb-supervisor/src/proxies/core.rs
orb-supervisor/src/tasks/update.rs
orb-supervisor/tests/it/helpers.rs

Brings the code up to the latest zbus version.

refactor: use zbus 4, migrate from deprecated macros

---

orb-ui/src/engine/diamond.rs
orb-ui/src/engine/mod.rs
orb-ui/src/engine/pearl.rs

will allow usage of the gimbal in the
"show-car" simulation

orb-ui: control the gimbal

---

Cargo.lock
Cargo.toml

we need to update tonic to 0.12.3 to fix the license check.
it's used by `console-subscriber` so I took the opportunity to update it from `0.2.0` to `0.4.0`.
Then I forced the usage of the latest tonic with:
```
❯ cargo update -p tonic --precise 0.12.3
Updating crates.io index
Updating tokio-stream v0.1.15 -> v0.1.16
Updating tonic v0.12.2 -> v0.12.3
```
I also checked that orb-ui can be built with the `tokio_unstable` config (that brings in the `console-subscriber`)

ci: update console-subscriber (and tonic dep)

---

orb-ui/cone/examples/cone-simulation.rs
orb-ui/rgb/src/lib.rs
orb-ui/src/engine/animations/arc_dash.rs
orb-ui/src/engine/animations/mod.rs
orb-ui/src/engine/animations/simple_spinner.rs
orb-ui/src/engine/animations/slider.rs
orb-ui/src/engine/animations/static.rs
orb-ui/src/engine/animations/wave.rs
orb-ui/src/engine/diamond.rs
orb-ui/src/engine/mod.rs
orb-ui/src/engine/pearl.rs

- `SignupStartOperator` event created for "legacy" flow where operator presses the button to start signup. 
- `SignupStart` now used to start signup/biometric capture:
- button press (v0 of self-serve)
- app button press by user (v1 of self-serve)
to be used with https://github.com/worldcoin/priv-orb-core/pull/1299

orb-ui: app-based self-serve ui

---

orb-ui/src/engine/diamond.rs
orb-ui/src/engine/pearl.rs

ui is paused when using orb-ui in api mode, to allow user to set ring colors etc.
but when starting core, the ui engine should resume.

orb-ui: allow switching between api and core modes

---

orb-ui/src/engine/animations/static.rs
orb-ui/src/engine/diamond.rs
orb-ui/src/simulation.rs

- fix fade-out transition
- modified success blinks to be smoother and in sync with the shroud fade out

orb-ui: smoother success animation

---

ci/rust_ci_helper.py
nix/shells/development.nix
orb-ui/Cargo.toml
orb-ui/debian/orb-ui.worldcoin-ui.service

Fixes the missing orb-ui binary. Also relocates it to /usr/local/bin.

ci: add check for missing binaries in .deb

---

orb-ui/rgb/src/lib.rs
orb-ui/src/engine/diamond.rs
orb-ui/src/engine/mod.rs
orb-ui/src/engine/pearl.rs
orb-ui/src/simulation.rs

differentiate between operator-based (legacy) and self-serve mode.
in operator-based mode, scanning the operator QR code shouldn't look like an error.
see https://github.com/worldcoin/priv-orb-core/pull/1367
fixes O-2903

orb-ui: operator qr scan

---

hil/src/download_s3.rs

AWS rust sdk is slow compared to cli, multipart download can speedup the process significantly,
see https://github.com/awslabs/aws-sdk-rust/discussions/1024. 
The logic for the change is mostly adapted from: https://github.com/smithy-lang/smithy-rs/blob/main/aws/sdk/benchmarks/s3-throughput/benchmark/src/multipart_get.rs.
For me the speedup was around 2x in Munich(It should be different for different latencies).
To be noted, that requests to s3 do cost something, but as I understood it's insignificant amount: https://aws.amazon.com/s3/pricing/?p=pm&c=s3&z=4. Lmk if I missed anything.
0.0004 $ per 1000 requests and with multi-part download we have ~40 requests per GB.

hil: Use multi-part download for hil

---

hil/src/download_s3.rs

Introduced a regression with my last PR, persist_noclobber will raise if file exists and was ignoring ovewrite behavior

fix(hil): fix a bug with overwriting existing rts file

---

mcu-util/src/main.rs
mcu-util/src/orb/revision.rs

error out on unknown hardware revision,
and don't write into file.
fixes O-2916

orb-mcu-util: hardware revision

---

mcu-util/src/main.rs
mcu-util/src/orb/main_board.rs
mcu-util/src/orb/mod.rs
mcu-util/src/orb/security_board.rs

for all commands
usage: orb-mcu-util --can-fd args
fixes O-2891

orb-mcu-util: add --can-fd option

---

mcu-interface/src/lib.rs

ack number uses the pid in the 16 most significant bits (and a counter in the lower 16 bits),
this allows us to filter out acks that are not
for the current process.
But, the pid can be encoded over more than 16 bits, so this fix allows the usage of the 16 lsb of the pid in the ack number, the msb of the pid are lost.
fixes that bug where the ack got ignored because the pid is higher than `u16::MAX`
```
2024-10-22T08:07:22.879010Z DEBUG orb_mcu_interface: Ignoring ack # 0xd013002b
2024-10-22T08:07:23.340840Z ERROR orb_mcu_util::orb::main_board: error asking for firmware version: ack not received (isotp)
```

can: fix ack number with a high pid

---

mcu-util/src/main.rs
mcu-util/src/orb/main_board.rs
mcu-util/src/orb/mod.rs

allows to trigger auto-home and set gimbal position for testing.
fixes O-2915

orb-mcu-util: control gimbal

---

ui/cone/examples/cone-simulation.rs
ui/rgb/src/lib.rs
ui/src/engine/animations/progress.rs
ui/src/engine/animations/simple_spinner.rs
ui/src/engine/animations/wave.rs
ui/src/engine/mod.rs
ui/src/engine/pearl/mod.rs
ui/src/engine/pearl/operator_based.rs
ui/src/engine/pearl/self_serve.rs
ui/src/main.rs

based on diamond ui
fixes O-2926

feat(ui): self-serve ui for pearl orbs

---

ui/rgb/src/lib.rs
ui/src/engine/diamond.rs
ui/src/engine/pearl/self_serve.rs
ui/src/simulation.rs

spinner with blue background for wifi qr code scanning

chore(orb-ui): animation for wifi qr code scanning in self-serve

---

Cargo.lock
Cargo.toml
telemetry/Cargo.toml
telemetry/src/lib.rs
ui/Cargo.toml
ui/examples/ui-replay.rs
ui/src/main.rs

we should in general be using journald for our logs, not stdout. Also, we should use stderr instead of stdout.
Every one of our crates sets up logging in a different way, but they all do the same thing. I wanted to introduce a single spot that lets us configure our telemetry. If it goes well in orb-ui, we can use it in all the rest too

telemetry: introduce orb-telemetry crate and use it in orb-ui

---

scripts/generate-new-orb-id/build/.gitignore
scripts/generate-new-orb-id/build/calibration.json
scripts/generate-new-orb-id/build/components.json
scripts/generate-new-orb-id/build/versions.json
scripts/generate-new-orb-id/gen-orb-id.sh

* Rewrite of orb-generation scripts and automatic registration

utils: generation of new orb-ids && registration support

---

Cargo.lock
artificer/Cargo.toml
attest/Cargo.toml
hil/Cargo.toml
update-verifier/Cargo.toml

`instant` crate is no longer maintained.
bumped crates that had `instant` as dependency. Luckily, these are not using it anymore.

fix(deny): bump crates with `instant` dependency

---

Cargo.lock
Cargo.toml
agentwire/Cargo.toml
agentwire/macros/Cargo.toml
agentwire/macros/src/broker.rs
agentwire/macros/src/lib.rs
agentwire/macros/src/test.rs
agentwire/src/agent/mod.rs
agentwire/src/agent/process.rs
agentwire/src/agent/task.rs
agentwire/src/agent/thread.rs
agentwire/src/lib.rs
agentwire/src/port.rs
agentwire/src/testing_rt.rs
agentwire/tests/process.rs
agentwire/tests/task.rs
agentwire/tests/thread.rs

Open-source `agentwire` framework.

feat(agentwire): Initial commit, extracted from `orb-core`

---

Cargo.lock
update-agent/CHANGELOG.md
update-agent/Cargo.toml
update-agent/src/update/can.rs

Backport changes from the now-archived update-agent repo.

fix(update-agent): increase ack timeout for mcu

---

Cargo.toml

The build fails with error:
> error[E0599]: the method `as_dyn_error` exists for reference `&Error`, but its trait bounds were not satisfied
>   --> update-agent/core/src/pubkeys.rs:76:21
>    |
> 76 |     InvalidPubKey(#[from] SignatureError),
>    |                     ^^^^ method cannot be called on `&Error` due to unsatisfied trait bounds
>    |
>   ::: /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/signature-2.2.0/src/error.rs:26:1
>    |
> 26 | pub struct Error {
>    | ---------------- doesn't satisfy `ed25519_dalek::ed25519::Error: AsDynError<'_>` or `ed25519_dalek::ed25519::Error: StdError`
>    |
>    = note: the following trait bounds were not satisfied:
>            `ed25519_dalek::ed25519::Error: StdError`
>            which is required by …

fix: update-agent build

---

update-agent/core/src/claim.rs
update-agent/core/src/lib.rs
update-agent/core/src/manifest.rs
update-agent/core/src/version_map.rs
update-agent/core/src/versions.rs
update-agent/src/component.rs
update-agent/src/main.rs

Update agent deviates from conventional rust coding pattern. For example it uses `&String` instead of `&str` and `&Option<String>` instead `Option<&String>`. 
I've also removed some structures like `version_map::ComponentInfo` and `version::ComponentInfo` (isn't it fun to have two different structures with the same name?)
--
I would appreciate comments about rust style/code quality and what else I could have refactored.

update-agent: refactor

---

update-agent/src/main.rs

If update-agent is run with `--nodbus` it should not try to reboot the orb using dbus API, instead it should fallback to calling `systemctl reboot`.

update-agent: don't use dbus if run with '--nodbus'

---

Cargo.lock
deny.toml

`cargo deny` which we run in CI checks for security advisories and ensures that licenses match an allowlist.
This PR does the following:
* adds Unicode-3.0 license to allowlist, it was used by one of our dependencies
* runs `cargo update -p url` to update the URL crate, so that it stops triggering `RUSTSEC-2024-0421`

fix(ci): address RUSTSEC-2024-0421 and allow Unicode-3.0

---

qr-link/src/lib.rs
qr-link/src/user_data.rs
qr-link/tests/verification.rs

Added new boolean field in the UserData struct to enable/disable age verification on the orb.

feat(qr-link): Age verification token field in UserData struct

---

update-agent/src/component.rs
update-agent/src/main.rs

update-agent could download OTA from a local directory. If the images are compress, update-agent tries to decompress files in the same directory where the source image is, instead of /mnt/downloads.
This commit makes update-agent decompress the images in /mnt/downloads.
--
From the patch it is impossible to understand the change, but that is just a nature of update-agent.

fix: OTA from local path

---

.cargo/config.toml
docker/cargo-runner.sh

lets mac users run tests that otherwise only run on linux.

build: add docker runner for mac users to run tests

---

update-agent/src/update/can.rs

diamond's main mcu uses an external flash that allows to use a larger image size, up to 448KiB.

feat(mcu-update): increase max mcu firmware size

---

Cargo.lock
Cargo.toml
attest/src/main.rs
attest/src/remote_api.rs
backend-state/src/main.rs
experiments/zenoh/src/main.rs
fleet-cmdr/src/main.rs
mcu-util/src/main.rs
supervisor/src/main.rs
supervisor/tests/it/helpers.rs
telemetry/Cargo.toml
telemetry/examples/async.rs
telemetry/examples/custom_filter.rs
telemetry/examples/simple.rs
telemetry/examples/sync.rs
telemetry/src/lib.rs
thermal-cam-ctrl/src/main.rs
ui/examples/ui-replay.rs
ui/src/main.rs
update-agent/src/main.rs
update-agent/tests/main.rs
update-verifier/src/main.rs

Adds tracing-opentelemetry as a tracing subscriber and also uses opentelemeyry-otlp to export spans to an opentelemetry collector

feat(telemetry): add opentelemetry support in orb-telemetry

---

Cargo.lock
Cargo.toml
endpoints/Cargo.toml
orb-info/Cargo.toml
orb-info/src/lib.rs
orb-info/src/orb_id.rs
orb-info/src/orb_jabil_id.rs
orb-info/src/orb_name.rs
orb-info/src/orb_token.rs
update-agent/Cargo.toml

* removed `from_env`, its just a wrapper around existing std library code
* removed `OrbInfoError` in favor of per-function errors. Its not necessary to have one big error type, and furthermore it complicates things since different feature flags result in some variants not being present
* Simplified some naming and removed code stuttering
*  Fixed blocking in async tests
* used Path instead of str when possible.
* removed `.value()`, because it added unecessary data hiding and also obscured potential bugs, since .borrow() does not notify the watcher that it was observed. Could result in much more frequent polling than intentional.
* Removed unnecessary dependencies and fixed a few sneaky spots where things did not have default-features = false
In general, lets be sure that we are not …

refactor(info): rework errors, general cleanup

---

Cargo.lock
Cargo.toml
experiments/webtransport_video/Cargo.toml
experiments/webtransport_video/index.html
experiments/webtransport_video/index.js
experiments/webtransport_video/src/main.rs
experiments/webtransport_video/src/networking.rs
experiments/webtransport_video/src/video.rs

This demos using webtransport to perform video streaming from the "orb" to the browser. It also demonstrates some ideas I had for efficient pools of frame buffers, as well as experiments with png encoding.
I think ultimately instead of png encoding, we should use an actual video codec + use the browser [WebCodecs](https://developer.mozilla.org/en-US/docs/Web/API/WebCodecs_API) api, instead of doing the jank png encoding. But even so, this works!

feat(wt_video): implement demo

---

cellcom/.dockerignore
test-utils/.dockerignore

Ensure .git and .gitignore are properly ignored
Prevent sensitive files from being included in Docker builds

chore: SEC-1406: Add .dockerignore

---

Cargo.lock
attest/Cargo.toml
attest/src/config.rs
attest/src/lib.rs

just was doing something else and noticed small cleanup chance

feat: add backend shared crate to orb-attest

---

Cargo.lock

ran `cargo update -p gpt` to bring in the latest commit from the `take-paitition` branch, which just changes the `~` semver to regular semver.

chore(update-agent): bump to minor tweak of gpt crate

---

Cargo.lock
Cargo.toml
deny.toml
gst-jpeg/Cargo.toml
gst-jpeg/README.md
gst-jpeg/src/lib.rs
nix/shells/development.nix

Used in orb-core livestream. In the future, it would be nice to detect the supported plugins and chose the ones supported on the host platform, instead of just being nvidia-only.

feat(gst-jpeg): hardware-accelerated jpg encode

---

mcu-util/src/main.rs
mcu-util/src/orb/main_board.rs

add commands to control rgb and booster leds
all leds are turned on for 3 seconds with the passed color
```
./orb-mcu-util ui front 
Test front leds for 3 seconds
Usage: orb-mcu-util ui front <COMMAND>
Commands:
red      
green    
blue     
white    
booster  
help     Print this message or the help of the given subcommand(s)
```
```
./orb-mcu-util ui front red
2025-03-10T12:12:06.870817Z  INFO orb_mcu_util::orb::main_board: 🚦 AllRed enabled
2025-03-10T12:12:09.874274Z  INFO orb_mcu_util::orb::main_board: LEDs disabled
```

feat(mcu-util): control front leds

---

.cargo/config.toml
.gitignore
docker/Dockerfile
docker/nix-cargo-runner.sh
docs/src/development.md
flake.nix
nix/containers/README.md
nix/containers/cargo-runner.nix
nix/containers/flake-outputs.nix
nix/shells/development.nix

I don't have a linux machine on me right now so I rely on running cargo tests. We have an existing cargo runner script that runs the tests in a debian docker container. But this is missing most of our actual dependencies. We need instead to actually build a docker image with all the necessary dependencies and use that.
https://linear.app/worldcoin/issue/ORBS-390/get-tests-to-run-in-cargo-runner-via-docker

feat(nix): build container for cargo tests

---

deny.toml
ui/rgb/src/lib.rs
ui/src/engine/animations/simple_spinner.rs
ui/src/engine/animations/wave.rs
ui/src/engine/diamond.rs
ui/src/engine/pearl/operator_based.rs
ui/src/engine/pearl/self_serve.rs
ui/src/simulation.rs

TODO
- @fouge : changed from 40 to 30. **But a problem arises, see below.**
- @fouge's comment: same time right now between in and out, but it's not noticeable: on pearl, the intensity is hard to control without bad UX: we notice the intensity **steps** when pulsing, on values close to 0. The animation should be smoother. More details: the current value goes from 1 to 30 using a sine wave. The intensity 29 to 30 is hardly noticeable if noticeable at all by the human eye (looks solid white), while the intensity from 1 to 2 is very noticeable (too much).
- **Let's use half the LEDs** to decrease general brightness: One idea to make it smooth: switch between which LEDs are on for each new frame. this might help to make sure we don't notice that we use only half the LED, because the light …

feat(ui): white during idle / user scanning (self-serve) 

---

Cargo.lock
Cargo.toml
bidiff-squashfs/lib/Cargo.toml
bidiff-squashfs/lib/src/lib.rs
hil/Cargo.toml

Tests with empty files fail due to segfault in C shim. I am marking these tests as `#[ignore]` so that fixing the offending code isn't a prerequisite for introducing tests.

test(bidiff-squashfs): add tests for different sqfs contents

---

ui/Cargo.toml
ui/rgb/src/lib.rs
ui/src/engine/animations/alert_v2.rs
ui/src/engine/animations/fake_progress_v2.rs
ui/src/engine/animations/mod.rs
ui/src/engine/diamond.rs
ui/src/engine/mod.rs
ui/src/engine/pearl/self_serve.rs
ui/src/sound/mod.rs

UX changes:
* biometric capture uses a fake progress animation coupled to finish (go to 100%) with the plan's timeout. If the capture is successful, `orb-core` issues a "fast-forward" command that also drives the progress to 100%.
* new biometric capture success animation:
* blink led ring twice and fade-out
* center led becomes green and fades-out in sync with the ring.
* after the capture, the orb remains blank until the next operator/user qr-scan.
* removed `SignupSuccess` animations
* removed `SignupFail` animations that come after biometric capture (pcp-upload/verification etc).
Codebase additions:
* new `alert_v2::Alert` animation for constructing pulse-train signals with (optionally) smooth transitions.
* new `fake_progress_v2::Progress` animation that gets configured by the …

refactor: orb-ui rework biometric-capture and after-capture animations

---

.github/workflows/rust-ci.yaml
Cargo.lock
Cargo.toml
hil/Cargo.toml
hil/src/download_s3.rs
nix/shells/development.nix
s3-helpers/Cargo.toml
s3-helpers/README.md
s3-helpers/examples/list.rs
s3-helpers/src/client.rs
s3-helpers/src/lib.rs
s3-helpers/src/list_prefix.rs
s3-helpers/src/s3_url_parts.rs
s3-helpers/tests/common/mod.rs
s3-helpers/tests/list_prefix.rs

Introduces the orb-s3-helpers crate to consolidate some common s3 related code between orb-hil and orb-bidiff-squashfs-cli.
Also introduces localstack for testing operations against s3, and implements list_prefix which will be used as part of orb-bidiff-squashfs-cli to download directories of s3 objects.

feat(s3-helpers): implement list_prefix

---

bidiff-squashfs/cli/src/diff_ota.rs
bidiff-squashfs/cli/src/main.rs

listen for ctrl-c on ota subcommand only. We only do that one because its the only one right now that is actually async. This lets us clean up temp dirs and run destructors.

fix(bidiff-squashfs): run destructors on ota subcommand

---

Cargo.lock
Cargo.toml
backend-status/Cargo.toml
backend-status/README.md
backend-status/build.rs
backend-status/dbus/Cargo.toml
backend-status/dbus/src/lib.rs
backend-status/debian/orb-backend-status.worldcoin-backend-status.service
backend-status/src/args.rs
backend-status/src/backend/mod.rs
backend-status/src/backend/models.rs
backend-status/src/backend/status.rs
backend-status/src/dbus.rs
backend-status/src/main.rs
backend-status/src/update_progress.rs

Orb Backend Status daemon:
- centralized implementation to send status updates to Orb backend
- receives updates over dbus `/org/worldcoin/BackendStatus1`
- listens to Update Agent `/org/worldcoin/UpdateAgentManager1` to send progress updates to backend

feat(backend-status): FM-405-orbsoft-backend-status

---

bidiff-squashfs/cli/src/diff_plan.rs
update-agent/core/src/claim.rs
update-agent/core/src/lib.rs
update-agent/core/src/manifest.rs

I mistakenly added a Deserialize impl on the update agent Claim. This is a bad idea, because the update agent performs verification on its claim in order to check the manifest signature.
I've removed my impl and instead I will use the `UncheckedClaim` in bidiff-squashfs.
I've also added the ability to serialize an UncheckedClaim.

feat(update-agent): remove deserialize, add serialize for Unchecked*

---

Cargo.lock
Cargo.toml
bidiff-squashfs/cli/Cargo.toml
bidiff-squashfs/cli/src/diff_ota.rs
bidiff-squashfs/cli/src/diff_plan.rs
update-agent/core/src/claim.rs
update-agent/core/src/components.rs
update-agent/core/src/file_location.rs
update-agent/core/src/manifest.rs

After [ORBS-407](https://linear.app/worldcoin/issue/ORBS-407/generate-diffing-plan) I realized that to execute the plan we would again need to have the deserialized claims and work with them.
I think a diffing plan is pretty useless if we don't include all the necessary information to actually do the file operations, so this PR reworks it:
* We validate all of the potentially failable operations and disk IO once per OTA dir, and store the extracted information in an `OtaDir` struct.
* The `DiffPlan::new` function then gets to be sans-io and non-failable.
* The operations have been reworked to only expose lower level information, and the actual paths that will be diffed or copied. This ensures that a Claim is not needed later in the plan execution phase.
* Overall due to the three steps …

refactor(bidiff-squashfs): simplify plan creation

---

Cargo.lock
Cargo.toml
backend-status/Cargo.toml
backend-status/dbus/Cargo.toml
backend-status/dbus/src/lib.rs
backend-status/dbus/src/types.rs
backend-status/src/args.rs
backend-status/src/backend/mod.rs
backend-status/src/backend/status.rs
backend-status/src/backend/types.rs
backend-status/src/dbus.rs
backend-status/src/main.rs
backend-status/src/update_progress.rs
endpoints/src/backend.rs
endpoints/src/v1.rs
endpoints/src/v2.rs
location/Cargo.toml
location/src/dbus.rs
telemetry/Cargo.toml
telemetry/src/lib.rs

- added dbus proxy to receive UpdateAgent progress messages
- support collecting and sending OrbStatusV2::UpdateProgressV2 to backend
- updated orb-endpoints::backend to support 'local' as an environment
- updated orb-telemetry to define a tracing object compatible with dbus
- used in orb-location -> orb-backend-status dbus

feat(backend-status): FM-405-orbsoft-backend-progress

---

Cargo.lock
Cargo.toml
io-utils/Cargo.toml
io-utils/src/clamped.rs
io-utils/src/lib.rs

Needed for binary diffing. We need to clamp a Read + Seek within a particular range.
This will get used to replace the current `gpt::TakePartition` code in the update agent which is inherently bugged when doing SeekFrom::End
tbh writing the test cases was hell :dizzy_face:

feat(io-utils): implement ClampedSeek

---

Cargo.lock

Fixes `cargo-deny` by updating the `openssl` dependency.

fix(ci): update openssl

---

ui/src/engine/animations/composites/biometric_flow.rs
ui/src/engine/animations/composites/mod.rs
ui/src/engine/animations/fake_progress_v2.rs
ui/src/engine/animations/mod.rs
ui/src/engine/animations/progress.rs
ui/src/engine/diamond.rs
ui/src/engine/mod.rs
ui/src/engine/pearl/self_serve.rs

1. Adds failure animation in case the processing phase returns an error. (red center LED & error sound).
2. Halting & Resuming the progress bar.
* Halts the progress bar when the user is not in range (also the music stops playing).
* Resumes the progress bar when the user enters the range, and the progress bar moves faster to catch-up with the "missed" progress. This is encouraging to the the user, as they did something positive (entered the correct range). (also the music playing resumes).
codebase changes: Introduces a new "composite" animation, which consists of the all the ux events that need to happen in a sequence during the signup (capturing and processing).

feat(ui): Pearl biometric-flow UX

---

attest/debian/orb-attest.worldcoin-attest.service

no need to call orb-id binary.

chore: on diamond ORB_ID is passed from the systemd

---

ui/rgb/src/lib.rs
ui/src/engine/diamond.rs

Removes the spinner, moves the color from the ring to the shroud (same as all other qr-scans), and makes the blue a bit darker.

chore(ui): diamond wifi qr-scan ux

---

ui/src/engine/diamond.rs

Clears the UI state on `boot_complete`.

feat(ui): diamond: clear ux on boot_complete

---

ui/src/engine/diamond.rs

`orb-core` will decide whether to play the voice or not based on the backend configuration.

chore(ui): diamond revive open_your_eyes_voice

---

hil/src/commands/login.rs

Configurable timeout is useful for many orb-hil use cases that require fast check of orb presence.

feat(hil): allow user to pass --timeout to login command

---

s3-helpers/Cargo.toml
s3-helpers/tests/common/mod.rs

switching from `localstack` to `minio` for testing S3 due to flakyness of localstack

chore(s3-helpers): switch to minio

---

update-agent/src/update/capsule.rs

On diamond, EFI System Partition has label ESP (uppercase), while on pearl it is `esp` (lowercase). Fix update-agent to find the ESP partition based on the partition type.
--
The check for multiple ESP partitions is explicitly required, because we have some orbs with multiple ESP partitions. I think all EVTs are like that.

fix: ESP partition mount

---

agentwire/src/port.rs

rust 2024 [introduces a change](https://rust-lang.github.io/rfcs/3617-precise-capturing.html#lifetime-capture-rules-2024) to how opaque types (like impl T) capture generics. The opaque types now capture *all* generics instead of only those that appear in the opaque type. 
In #551 we upgraded to rust 2024, which means that the generics captured by opaque types are capturing *more* generics than previously intended - this is called ["overcapturing"](https://rust-lang.github.io/rfcs/3617-precise-capturing.html#background). As an example of this, consider [this function signature](https://github.com/worldcoin/orb-software/blob/12d0881c93458d56e248c87af16235466ae3506a/agentwire/src/port.rs#L375) from agentwire:
```rust
pub fn chain_fn(&self) -> impl Fn(T::Output) -> Output<T> {
let source_ts = …
```

fix(agentwire): use precise captures to match pre-2024 edition

---

nix/machines/home-hil.nix

nvim failed with treesitter errors because the treesitter plugin was too old for the latest neovim.

chore(hil): update nvim config

---

nix/shells/tegra-bash.nix

the fhsenv was missing various libraries needed for the new flashing scripts.

fix(hil): update tegra-bash.nix for diamond

---

Cargo.lock
jobs-agent/Cargo.toml
jobs-agent/src/args.rs
jobs-agent/src/handlers/mod.rs
jobs-agent/src/main.rs

This PR makes two specific changes:
1. Add support for the FAILURE_UNSUPPORTED job status to indicate when a jobs-agent is unable to process a job, as it does not have a corresponding handler. This will help us diagnose job failures related to out of date jobs-agents in the field.
2. Use the orb_info package to read information about the orb ID if it's not passed via the CLI args.

feat: Add FAILURE_UNSUPPORTED job status to jobs agent and utilize orb_info

---

jobs-agent/debian/worldcoin-jobs-agent.service
jobs-agent/src/args.rs

Also corrects the relay namespace that the orb-jobs-agent uses to communicate with the jobs server.

fix: Fix dbus env setting in worldcoin-jobs-agent service file

---

nix/machines/hil-common.nix
nix/machines/nixos-common.nix
nix/shells/tegra-bash.nix

This PR does several things:
* adds the necessary packages to the `tegra-bash` FHSEnv to enable the use of the boot-from-ram bootloader0 scripts.
* Configures a known name for the network interface of the orb's RCM ethernet, based on VID and PID, and names it `orbeth0`. This allows us to replicate our configuration across many orbs and NUCs.
* Configures a networkmanager connection for `orbeth0`, in particular setting it as a "shared" connection, which will cause the orb to run a DHCP server to assign ip addresses to the orb - necessary for NFS.
* Configures the NUC to run a NFS server. Anything under `/srv` will be exposed to the orb over NFS, and only on the local ipv4 10.42.0.0/24 subnet.
* Configures port forwarding for the NFS server.

feat(hil): expose nfs

---

mcu-util/src/main.rs
mcu-util/src/orb/main_board.rs
mcu-util/src/orb/mod.rs
mcu-util/src/orb/security_board.rs

show hardware states when `--diag` is passed with `info` command
full command: 
```
./orb-mcu-util info --diag
🔮 Orb info:
revision:	Diamond_DVT1
battery charge:	13%
voltage:	13430mV
charging:	no
🚜 Main board:
current image:	v3.1.7-0x0 (dev)
secondary slot:	v1.2.3-0x4 (prod)
🔐 Security board:
current image:	v3.1.5-0x0 (dev)
secondary slot:	v37.100.0-0x54534557 (prod)
battery charge:	100%
voltage:	4130mV
charging:	no
🛠️ Hardware states:
als          STATUS_SUCCESS                      
fan_tach     STATUS_SUCCESS                      
ir_self      STATUS_ERROR_INVALID_PARAM          💎️safety self-test not impl
polarizer    STATUS_SUCCESS                      homed
pvcc         STATUS_SUCCESS                      ir leds usable
sound        STATUS_SUCCESS                      
tmp_front …
```

feat(mcu-util): diag data

---

orb-blob/tests/health.rs

prevents confusing messages on the terminal when tests are run

chore(blob): change test ok to more descriptive name

---

orb-blob/p2p/src/hash.rs
orb-blob/p2p/src/lib.rs

gossip protocols deduplicate messages. This ensures each rebroadcast is seen as a unique message.

fix(blobs): random nonce with each broadcast

---

orb-blob/p2p/tests/two_peers_1_bootstrap.rs
orb-blob/tests/e2e_node_share.rs

just in case we are using secretkeys in our tests that others on the iroh discovery service are using, this will help avoid collisions.

fix(blobs): better seeds for keys

---

orb-blob/src/program.rs
orb-blob/tests/blob_create.rs
orb-blob/tests/blob_delete.rs
orb-blob/tests/e2e_node_share.rs
orb-blob/tests/fixture.rs
orb-blob/tests/health.rs

Its an error to try and broadcast when there are no bootstrap nodes, and the library (intentionally) panics. We should stop attempting to broadcast in cases where we are the only node / we have no bootstrap nodes.

fix(blobs): stop broadcasting when no bootstrap

---

nix/machines/hil-common.nix

avoids permission errors on the client due to `no_root_squash`, and `crossmnt` allows nested mounts to be exposed to the client.

fix(hil): NFS permissions and nested mounts

---

jobs-agent/debian/worldcoin-jobs-agent.service

adds jobs-agent to `systemd-journal` group in order to be able to read logs

chore(jobs-agent): add to systemd-journal group

---

jobs-agent/src/main.rs

always use /mnt/scratch as store path

fix(jobs-agent): always use /mnt/scratch as store path

---

jobs-agent/src/handlers/logs.rs
jobs-agent/src/handlers/reboot.rs
jobs-agent/src/job_system/client.rs
jobs-agent/src/job_system/handler.rs
jobs-agent/src/job_system/orchestrator.rs
jobs-agent/src/settings.rs
jobs-agent/tests/common/fixture.rs
jobs-agent/tests/job_handler.rs
jobs-agent/tests/reboot.rs

- add a test to be sure cancelling a job works
- memory leak when tailing logss
- race condition due `JobClient::listen_for_jobs` not including ids to ignore and main handle function not checking if id is of a job already running
- lack of retry for `AuthToken` acquisition

test(jobs-agent): test canceling a job works

---

Cargo.lock
jobs-agent/Cargo.toml
jobs-agent/README.md
jobs-agent/src/handlers/reboot.rs
jobs-agent/src/job_system/client.rs
jobs-agent/src/job_system/handler.rs
jobs-agent/src/job_system/orchestrator.rs
jobs-agent/tests/check_my_orb.rs
jobs-agent/tests/common/fixture.rs
jobs-agent/tests/common/job_queue.rs
jobs-agent/tests/common/mod.rs
jobs-agent/tests/job_handler.rs
jobs-agent/tests/orb_details.rs
jobs-agent/tests/read_file.rs
jobs-agent/tests/reboot.rs
test-utils/src/async_bag.rs

- race condition if a job completes a job, but ends up requesting a new job before the server has time to remove it from its queue
- test for the above race  condition
- test we return FailedUnsupported for unknown jobs
- updated readme

fix(jobs-agent): race condition whenrequesting a new job

---

flake.lock

fixes `evaluation warning: rust.toRustTarget platformis deprecated. Useplatform.rust.rustcTarget instead.`

chore(nix): bump fenix to silence warning

---

jobs-agent/src/program.rs
jobs-agent/tests/reboot.rs

disabling the reboot command temporarily due to:
- nvidia retry counter decreasing on every reboot (as opposed to full power cycle)
- `orb-mcu-util reboot main` has a bug where orb isn't powered back on, so we can't use it instead yet

chore(jobs-agent): disable reboot command

---

hil/src/commands/flash.rs
hil/src/commands/nfsboot.rs
hil/src/nfsboot.rs
hil/src/rts.rs

We are gonna need the persistent files populated both when we flash and when we do the mounting of the nfs. Therefore lets break it out into its own function to be more explicit about the ordering of things.

refactor(hil): break persistent population out of flash fn

---

backend-status/dbus/src/types.rs
backend-status/src/backend/status.rs
backend-status/src/backend/types.rs
backend-status/src/dbus/intf_impl.rs

- Reuse the existing WifiNetwork status type

fix: orb_backend_status_types_redux

---

nix/machines/hil-common.nix

We need `sudo` to perform the bind mounts, etc. Unfortunately this wasn't working on the sandboxed NixOS runner. I've gone and disabled more sandboxing things, and most importantly, I've added the nixos sudo wrapper to the PATH.

fix(hil): enable sudo on github runner

---

.github/workflows/update-agent.yml
.gitignore
Cargo.lock
update-agent/Cargo.toml
update-agent/core/Cargo.toml
update-agent/core/src/components.rs
update-agent/src/update/capsule.rs
update-agent/t/qemu-runner.js

Depending on the orb model, storage device could be:
- Pearl - `/dev/mmcblk0`
- Diamond with SD Express card: `/dev/nvme0n1`
- Diamond with SD card `/dev/mmcblk1`
In the past that was expressed in the claim, by specifying device type 'nvme'(for `/dev/nvme0n1`) or 'emmc' (for `/dev/mmcblk0`). 
We need to add support for Diamond with plain SD card (`/dev/mmcblk1`). We have an option to add yet another device type, but that will make manifest generation more complicated and will split the fleet even further. 
Instead of adding more device types. I propose to have only one device type SSD (solid state drive).  And detect the storage device used by checking where the `/usr/persistent/` is mounted.

fix: storage discovery

---

nix/machines/hil-common.nix

we weren't able to `sudo mount` in the github runner.

fix(hil): increase cap bounding set for github runner

---

hil/src/commands/login.rs
nix/machines/hil-common.nix

We were getting log messages like:
```
2025-08-29T19:47:59.921716Z  INFO orb_hil::commands::login: Detected login prompt!
2025-08-29T19:48:00.122286Z  INFO orb_hil::commands::login: Entering username
localhost login: worldcoin
2025-08-29T19:48:00.324010Z  INFO orb_hil::commands::login: Entering password
***
Password: 
```
Which made it seem that maybe we were waiting too little time between username and password. Previously we delayed 200ms, now we delay 2000ms.

fix(hil): slightly increase delay between username and pass

---

update-verifier/debian/orb-update-verifier.worldcoin-update-verifier.service
update-verifier/src/lib.rs

when booting, isotp errors are detected on the mcu side because both worldcoin-create-hardware-version and update-verifier are trying to communicate with the mcu over iso-tp with the same pair of addresses
use can-fd to prevent that issue from happening

fix(iso-tp): orb-mcu-util with can-fd

---

Cargo.lock
Cargo.toml
deny.toml
mcu-util/Cargo.toml
ui/cone/Cargo.toml

to use adler2 instead of the unmaintained adler crate
update `image` dep (and remove from mcu-util, unused)

fix(deny): unmaintained crates, and allow NCSA license

---

update-agent/src/component.rs

@AlexKaravaev found that update-agent is not `error-ing` when `orb-mcu-util` fails.
We were not checking the return value of the `status`.

fix(update-agent): check against orb-mcu-util errors

---

orb-jobs-agent/debian/worldcoin-jobs-agent.service
orb-jobs-agent/src/handlers/check_my_orb.rs
orb-jobs-agent/src/handlers/mod.rs
orb-jobs-agent/src/handlers/wifi_ip.rs
orb-jobs-agent/src/program.rs

This pull request adds a new handler for retrieving the WiFi IP address and improves the flexibility of the `check_my_orb` command. It also updates the systemd service dependencies to ensure proper startup order. The most important changes are grouped below:
* Added the `wifi_ip` handler to provide the IP address of the currently connected WiFi interface, including detection logic and output formatting. (`orb-jobs-agent/src/handlers/wifi_ip.rs`)
* Registered the new `wifi_ip` handler in the module exports and the job system, making it available for use. (`orb-jobs-agent/src/handlers/mod.rs`, `orb-jobs-agent/src/program.rs`) [[1]](diffhunk://#diff-828c40d1bb4e8a2bc1a35351f4a0549510dc8c0b004035a96277f1a83096a409R8) [[2]](diffhunk://#diff-6ef7e04362a7d78e147b3e7ed0702028b79c0fe368c0284d1ba85f …

feat: Add support for --json flag in check-my-orb and new wifi_ip handler

---

ui/rgb/src/lib.rs
ui/src/engine/diamond.rs

Removes the blue static color of the wifi-qr-scan phase.
Introduces a breathing animation. The sine-wave high color is equal to user-qr-scan, and low is `Argb::Off`.

chore(ui): wifi qr scan animation

---

Cargo.lock
deny.toml
flake.lock

github runners needed an update. I took the opportunity to just update everything in the flake inputs. Also required changing deny.toml

chore(nix): bump flake inputs to fix github runner
