- README.md
max-jobs should be it's own line
> readme: Include appropriate newline in nix.conf

- orb-ui/src/engine/diamond.rs
- orb-ui/src/engine/mod.rs
- orb-ui/src/engine/pearl.rs
Regression introduced with orb-ui
https://github.com/worldcoin/priv-orb-core/pull/1134
> ui: Indicate invalid qr codes with a voice

- orb-ui/src/engine/diamond.rs
- orb-ui/src/engine/mod.rs
- orb-ui/src/engine/pearl.rs
used to indicate that wifi has successfully connected
only played after wifi qr is requested
goes with https://github.com/worldcoin/priv-orb-core/pull/1141
> orb-ui: resurrect network connection success sound

- Cargo.lock
- orb-ui/src/engine/diamond.rs
- orb-ui/src/engine/pearl.rs
> orb-ui: remove logging of each UI event

- .github/workflows/release.yaml
Also sets the default one to LL.
> ci: configurable release version

- Cargo.lock
- Cargo.toml
- mcu-util/src/orb/security_board.rs
> deps: update orb-messages to latest

- mcu-interface/src/can/canfd.rs
so that we don't receive and parse messages handled by another CanRawMessaging
otherwise we end up with `debug!("Ignoring empty message")` in `handle_sec_mcu_message` & `handle_main_mcu_message`
> mcu-interface: filter out only messages from device

- mcu-util/src/main.rs
Slightly nicer CLI experience.
> mcu-util: add colors

- orb-qr-link/src/user_data.rs
This PR fixes the issue reported here: https://github.com/worldcoin/priv-orb-core/pull/1188#issuecomment-2178909426
> orb-qr-link: Fix backward incompatibility

- orb-ui/src/engine/diamond.rs
Add missing voice to ask for wifi QR on Diamond.
> orb-ui: Add missing voice to ask for wifi QR on Diamond

- mcu-util/src/orb/main_board.rs
- mcu-util/src/orb/security_board.rs
> orb-mcu-util: security mcu to apply update directly

- Cargo.lock
- Cargo.toml
contains fixed source for front unit sensors
> orb-messages: update to latest

- Cargo.lock
- orb-qr-link/Cargo.toml
- orb-qr-link/src/lib.rs
- orb-qr-link/src/user_data.rs
- orb-qr-link/tests/verification.rs
@marioradonic @danielle-tfh I think this can help us actually transition to full app-centric easier. Let me know of your thoughts.
> orb-qr-link: Signal user-centric signups

- orb-ui/src/engine/diamond.rs
> orb-ui: normalize brightness at top and bottom of outer ring

- orb-ui/src/dbus.rs
- orb-ui/src/main.rs
- orb-ui/src/simulation.rs
- orb-ui/src/sound/mod.rs
easy ways to test
```
orb-ui simulation <mode>
```
simulations modes:
- `operator` legacy flow
- `self-serve` 
- `show-car`
- to test: `sudo echo 441 > /sys/class/gpio/export` to set button as GPIO input
> orb-ui: simulations & show-car

- orb-ui/sound/src/queue.rs
- orb-ui/src/engine/diamond.rs
- orb-ui/src/engine/pearl.rs
- orb-ui/src/sound/mod.rs
no need for an option where the default can be used
fixes ORBP-266
> orb-ui: use Duration::ZERO instead of Option<Duration>

- mcu-util/src/main.rs
to prevent useless writes to flash.
++ use tokio::fs instead of std::fs
> orb-mcu-util: hw rev: overwrite file if content is different

- orb-ui/src/engine/diamond.rs
- orb-ui/src/simulation.rs
with 3-second period
temporary workaround?
> orb-ui: pulsates ring with a breathe/wave animation.

- orb-ui/src/engine/animations/simple_spinner.rs
- orb-ui/src/engine/diamond.rs
qr capture animations, smoother transitions, faster error alert
> ui: diamond: tweaked a few animations

- .github/workflows/check-sound-files.yaml
> ci: fix paths to ui script

- .github/workflows/check-sound-files.yaml
I would like to explicitly name it so that in the required status checks, its more clear.
> chore(ci): Give explicit name to sound file check

- scripts/remote-provision.sh
> scripts: supporting remote re-provisioning

- Cargo.lock
- mcu-util/Cargo.toml
- mcu-util/warn_renamed.sh
- thermal-cam-ctrl/warn_renamed.sh
Also adds the renaming script that @alekseifedotov had written for orb-os.
> chore(mcu-util): move to /usr/local/bin

- Cargo.lock
- Cargo.toml
- backend-state/Cargo.toml
- backend-state/debian/orb-backend-state.worldcoin-backend-state.service
- backend-state/src/api.rs
- header-parsing/Cargo.toml
Service file comes from orb-os.
> chore(backend-state): move to /usr/local/bin and add .service file

- Cargo.lock
- Cargo.toml
- header-parsing/Cargo.toml
- hil/Cargo.toml
- security-utils/Cargo.toml
Bump reqwest version to the latest.
> chore(cargo): bump reqwest version

- .github/workflows/delete-tmp-release.yaml
- .github/workflows/pr-compliance.yaml
- .github/workflows/python-ci.yaml
- .github/workflows/release.yaml
- .github/workflows/rust-ci.yaml
Waiting for infra to add the 24.04 runner
> chore(ci): bump to latest runners

- endpoints/src/backend.rs
- endpoints/src/endpoints.rs
We need to support a new Analysis backend with its own set of endpoints.
> feat(orb-endpoints): Add a new Analysis backend

- hil/src/serial/mod.rs
Orbs now have different than localhost hostname
> fix(hil): Make login pattern more generic for hil

- scripts/upload-certs.sh
Same mistake as https://github.com/worldcoin/orb-software/pull/335/files
Skill issue :(
> fix(upload-certs): vol 3

- update-agent/src/component.rs
Fix on [PR](https://github.com/worldcoin/orb-software/pull/330):
The dst that was passed into `component.process()`, made the `xz` components always look for the `dst` instead the component specific file under `dst/component-unique-name`.
This was forcing all the compressed components to `reprocess` and actually due to the size of the `downloads` directory the `size` check in the CAN components was constantly failing the update-agent.
Additionally we were not following the notion of `.verified` file flags for the `uncompressed` components but were overwriting the one that already existed from the component fetching process.
> fix(update-agent): fix destination on xz components (ORBS-241)

- Cargo.lock
- Cargo.toml
- cellcom/Cargo.toml
- cellcom/Dockerfile
- cellcom/README.md
- cellcom/src/bin/simple.rs
- cellcom/src/cell/data.rs
- cellcom/src/cell/mod.rs
- cellcom/src/cell/parser.rs
- cellcom/src/cell/types.rs
- cellcom/src/data.rs
- cellcom/src/geoloc.rs
- cellcom/src/lib.rs
- cellcom/src/main.rs
- cellcom/src/wifi.rs
Adds `cellcom`, a project to get localization information using data from wpa_supplicant and the Quectel EC25 module.
> feat: add cellcom (localization)

- mcu-util/src/main.rs
- mcu-util/src/orb/main_board.rs
command to trigger IR LED + eye or face camera until it's automatically deactivated.
default settings are used with 850nm IR LED set for a duration of 300us.
helping @Qbicz setting up camera
> feat(mcu-util): trigger camera command

- ui/src/engine/mod.rs
- ui/src/main.rs
- ui/src/serial.rs
- change serial interface name to `ttyTHS1`
- change number of leds in the ring
> feat(ui): support for diamond evt

- Cargo.lock
- Cargo.toml
- deny.toml
- fleet-cmdr/Cargo.toml
- fleet-cmdr/src/handlers/cmd_orb_details.rs
- fleet-cmdr/src/handlers/cmd_read_file.rs
- fleet-cmdr/src/handlers/cmd_reboot.rs
- fleet-cmdr/src/handlers/cmd_run_binary.rs
- fleet-cmdr/src/handlers/cmd_tail_logs.rs
- fleet-cmdr/src/handlers/mod.rs
Fleet Commander
- Command: check_my_orb
- Command: mcu_info
- Command: read_gimbal
- Command: tail_core_logs
> feat(fleet-cmdr): FM-191-fleet-cmdr-check-my-orb

- .github/workflows/gh-pages.yml
- .github/workflows/nix-ci.yaml
- .github/workflows/python-ci.yaml
- .github/workflows/release.yaml
- .github/workflows/rust-ci.yaml
- .github/workflows/update-agent.yml
Change token name to ORB_GIT_HUB_TOKEN
> build: Change token name INFRA-3216

- .github/workflows/release.yaml
Added `orb-fleet-cmdr` component option to gh action
> feat(fleet-cmdr): Update release.yaml

- Cargo.lock
- Cargo.toml
- mcu-util/src/orb/revision.rs
main board version 4.4 is Diamond_EVT
> feat(mcu-util): diamond: evt main board version

- .github/workflows/release.yaml
- added `orb-location` component option
> feat(location): Update release.yaml

- Cargo.lock
- Cargo.toml
- location/daemon/Cargo.toml
- location/daemon/src/main.rs
- location/wifi/Cargo.toml
- location/wifi/README.md
- location/wifi/src/iw.rs
- location/wifi/src/lib.rs
- location/wifi/src/wpa.rs
- location/wpa-supp/README.md
@Michael-Preibisch wrote this code, I'm just pulling it into a PR as part of the rebase after the force push. Also added him to authors of the crate
> feat(location): implement network scanning with iw cli

- Cargo.lock
- location/cellcom/src/data.rs
- location/daemon/Cargo.toml
- location/daemon/src/lib.rs
- location/daemon/src/network_manager.rs
- location/google-geolocation-api/src/support.rs
@Michael-Preibisch is the author, I'm just merging as part of the rebase. Also added him to orb-location crate authors
> feat(location): implement network manager datastructure

- endpoints/src/v2.rs
@Michael-Preibisch is author, this is part of the rebase.
> fix(endpoints): update v2 status endpoint

- Cargo.lock
- Cargo.toml
- location/daemon/Cargo.toml
- location/daemon/src/backend/status.rs
- location/daemon/src/config.rs
- location/daemon/src/errors.rs
- location/daemon/src/lib.rs
- location/daemon/src/main.rs
- location/daemon/src/network_manager.rs
- location/daemon/src/service.rs
- location/google-geolocation-api/src/support.rs
- location/wifi/src/wpa.rs
@Michael-Preibisch wrote the PR
> feat(location): turn into actual daemon

- Cargo.lock
- Cargo.toml
- bidiff-squashfs/cli/Cargo.toml
- bidiff-squashfs/cli/build.rs
- bidiff-squashfs/cli/src/diff_ota.rs
- bidiff-squashfs/cli/src/fetch.rs
- bidiff-squashfs/cli/src/lib.rs
- bidiff-squashfs/cli/src/main.rs
- bidiff-squashfs/cli/src/ota_path.rs
- hil/Cargo.toml
- s3-helpers/Cargo.toml
- s3-helpers/tests/common/mod.rs
- s3-helpers/tests/common_tests.rs
- s3-helpers/tests/download_multipart.rs
Implements the OTA fetching and progress bars etc.
> feat(bidiff-squashfs): fetch OTAs

- Cargo.lock
- Cargo.toml
- mcu-util/src/orb/main_board.rs
- mcu-util/src/orb/security_board.rs
show when ack returns an error
> feat(mcu-util): better ack error handling

- .github/workflows/release.yaml
new package: orb-backend-status
> feat(backend-status): Update release.yaml

- mcu-util/src/orb/main_board.rs
- mcu-util/src/orb/revision.rs
- mcu-util/src/orb/security_board.rs
conversion from int to enum
remove unimplemented ValueGet:
- battery status for main mcu
- hardware version for security board
> fix(mcu-util): fix hw revision reading

- Cargo.lock
- Cargo.toml
- arc-pool/Cargo.toml
- arc-pool/README.md
- arc-pool/src/lib.rs
Used in orb-core's livestream to reuse buffers
> feat(arc-pool): initial commit

- Cargo.lock
- backend-status/dbus/src/types.rs
- backend-status/src/backend/status.rs
- backend-status/src/dbus.rs
- backend-status/src/main.rs
- location/Cargo.toml
- location/src/dbus.rs
- telemetry/src/lib.rs
- these zvariant signatures fix dbus serialization failures
> feat(backend-status): FM-405-orbsoft-backend-status-fix

- Cargo.lock
- Cargo.toml
- mcu-util/src/orb/security_board.rs
ping allows sending big chunks of data over isotp for testing
will help fix ORBP-678
> feat(mcu-util): new stress command

- ui/src/engine/animations/fake_progress_v2.rs
- ui/src/engine/animations/progress.rs
Adds the ability to halt/resume fake-progress
> feat(ui): halt/resume fake-progress

- Cargo.lock
- Cargo.toml
- update-agent/Cargo.toml
- update-agent/core/src/components.rs
- update-agent/src/update/can.rs
- update-agent/src/update/capsule.rs
- update-agent/src/update/gpt.rs
- update-agent/src/update/mod.rs
- update-agent/src/update/raw.rs
- update-agent/tests/main.rs
> refactor(update-agent): get rid of gpt fork and TakePartition

- Cargo.lock
- backend-state/debian/orb-backend-state.worldcoin-backend-state.service
- backend-status/debian/orb-backend-status.worldcoin-backend-status.service
- backend-status/src/args.rs
- deny.toml
- debian package typos
- removed internal arg default
> fix(backend-status): FM-405-orbsoft-backend-status-tweaks

- .github/workflows/release.yaml
This reverts commit dba9155b5c7b9e5af87dbc303008050957bc9ff5.
> chore(ci): revert remove draft (#467)

- backend-status/src/args.rs
- backend-status/src/backend/status.rs
- backend-status/src/dbus.rs
- backend-status/src/main.rs
- moved orb and token initialization to main
- default to 30 second updates
- updated args
> fix(backend-status): FM-405-orbsoft-backend-status-defaults

- ui/src/engine/animations/composites/mod.rs
- ui/src/engine/animations/composites/positioning.rs
- ui/src/engine/diamond.rs
During preflights (before progress bar begins) LED ring becomes red when the user is in the wrong position.
> feat(ui): diamond positioning ux

- backend-status/dbus/src/types.rs
- backend-status/src/backend/mod.rs
- backend-status/src/backend/os_version.rs
- backend-status/src/backend/status.rs
- backend-status/src/backend/types.rs
- backend-status/src/update_progress.rs
A little more infallible implementation of 'try connect' which detects if the update agent dbus is present
> fix(backend-status): FM-434 dbus connection check

- backend-status/debian/orb-backend-status.worldcoin-backend-status.service
- fleet-cmdr/debian/fleet-cmdr.worldcoin-fleet-cmdr.service
- location/debian/orb-location.worldcoin-location.service
add RestartSec=10s to backend_status, location, fleet-cmdr
> fix(backend-status): service daemon restart delay

- backend-status/src/backend/status.rs
- backend-status/src/backend/types.rs
- backend-status/src/dbus/intf_impl.rs
- backend-status/src/main.rs
- Collect orb name and jabil id in status to send to orb backend
So Fleet Commander can search by these
> feat(backend-status): Collect orb name and jabil id in status

- Cargo.lock
- Cargo.toml
- mcu-util/src/main.rs
- mcu-util/src/orb/main_board.rs
home polarizer wheel
set specific glass or custom angle
> feat(mcu-util): add commands to control polarizer

- Cargo.lock
- Cargo.toml
- mcu-util/src/orb/security_board.rs
on `info` command, synchronize time with security mcu.
> feat(mcu-util): send time to security mcu

- Cargo.lock
- Cargo.toml
- mcu-util/src/orb/revision.rs
hardware version set to `Diamond_DVT`
> feat(mcu-util): recognize dvt boards

- mcu-util/src/orb/revision.rs
> fix(mcu-util): recognize dvt

- efivar/src/lib.rs
I need to pump the number of PRs
> fix: typo mutalbe -> mutable

- agentwire/macros/src/broker.rs
Same idea as #553 but this time for broker attributes.
Before this pr:
```
error[E0599]: no method named `poll_extra` found for mutable reference `&mut Broker` in the current scope
--> orb-core/agent-iroh/examples/broker.rs:11:10
|
11 | #[derive(Broker)]
|          ^^^^^^ this is an associated function, not a method
|
= note: found the following associated functions; to be used as methods, functions must have a `self` parameter
note: the candidate is defined in an impl for the type `Broker`
--> orb-core/agent-iroh/examples/broker.rs:40:5
|
40 |     fn poll_extra() -> Result<Option<()>> {
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
= note: this error originates in the derive macro `Broker` (in Nightly builds, run with -Z macro-backtrace for more info)
```
After this PR:
```
error[E0599]: …
```
> feat(agentwire): use quote_spanned!() for broker attributes

- .github/workflows/nix-ci.yaml
- flake.lock
- flake.nix
- nix/machines/disko-bios-uefi-liveusb.nix
- nix/machines/flake-outputs.nix
- nix/machines/hil-common.nix
- nix/machines/home-hil.nix
- nix/machines/home-liveusb.nix
- nix/machines/liveusb/configuration.nix
- nix/machines/liveusb/hardware-configuration.nix
- nix/machines/nixos-common.nix
- nix/machines/ryan-worldcoin-hil/hardware-configuration.nix
- nix/machines/worldcoin-hil-jabil-0/hardware-configuration.nix
- nix/machines/worldcoin-hil-munich-0/hardware-configuration.nix
- nix/machines/worldcoin-hil-munich-1/hardware-configuration.nix
- nix/machines/worldcoin-hil-sf-0/hardware-configuration.nix
- nix/overlays/nixpkgs-23_11.nix
- nix/overlays/unstable.nix
- nix/packages/nixpkgs.nix
- nix/xdg/zellij.kdl
bumps the NixOS version to nixpkgs stable (25.05).
> chore(hil): bump to 25.05

- Cargo.lock
- Cargo.toml
- mcu-util/src/main.rs
- mcu-util/src/orb/main_board.rs
wifi power can only be switched with a debug firmware
> feat(mcu-util): power cycle heat camera power & wifi/ble module

- Cargo.lock
- thermal-cam-ctrl/Cargo.toml
> feat: bump thermal-cam-ctrl to 0.0.8

- mcu-util/src/orb/main_board.rs
to trigger broadcast of all the messages over can-fd as this will add a subscriber.
Regardless of the preferred communication protocol (isotp or canfd).
since worldcoin-mcu-telemetry starts only when internet connection is alive, we need orb-mcu-util to trigger broadcast of all the messages so that battery can be known (relying on messages sent every second)
> chore(mcu-util): send one can-fd message

- Cargo.lock
- Cargo.toml
- orb-blob/Cargo.toml
- orb-blob/p2p/Cargo.toml
- orb-blob/p2p/README.md
- orb-blob/p2p/src/hash.rs
- orb-blob/p2p/src/lib.rs
- orb-blob/p2p/src/tag.rs
basic scaffold and directory structure.
> chore(blob): scaffold p2p crate

- Cargo.lock
- Cargo.toml
- orb-blob/p2p/Cargo.toml
- orb-blob/p2p/src/bootstrap.rs
- orb-blob/p2p/src/hash.rs
- orb-blob/p2p/src/lib.rs
- orb-blob/p2p/src/tag.rs
* simplistic parsing for tags and domains
* bootstapper to discover boostrap NodeIds
* gossip listening
> feat(blob): gossip listener, bootstrapper

- Cargo.lock
- Cargo.toml
- orb-blob/Cargo.toml
- orb-blob/p2p/src/hash.rs
- orb-blob/p2p/src/lib.rs
- orb-blob/src/cfg.rs
- orb-blob/src/handlers/blob.rs
- orb-blob/src/handlers/download.rs
- orb-blob/src/handlers/mod.rs
- orb-blob/src/program.rs
- orb-blob/tests/blob_create.rs
- orb-blob/tests/blob_delete.rs
- orb-blob/tests/e2e_node_share.rs
- orb-blob/tests/fixture.rs
- orb-blob/tests/health.rs
this is a description
we are all in the same room
we are in a hackathon
we live in a society
or something
> feat(orb-blob): upload download flow plus e2e tests

- orb-blob/p2p/Cargo.toml
- orb-blob/p2p/src/hash.rs
- orb-blob/p2p/src/lib.rs
- orb-blob/p2p/src/tag.rs
- orb-blob/p2p/tests/two_peers_1_bootstrap.rs
- orb-blob/src/handlers/download.rs
- orb-blob/src/program.rs
See https://linear.app/worldcoin/issue/ORBS-540/rework-api-to-deal-with-misunderstanding-of-how-bootstrap-nodes-work
> fix(blobs): redesign around concept of BlobRef

- .github/workflows/rust-ci.yaml
- Cargo.lock
- orb-blob/Cargo.toml
- orb-blob/p2p/Cargo.toml
- orb-blob/p2p/src/lib.rs
- orb-blob/p2p/tests/two_peers_1_bootstrap.rs
- orb-blob/src/handlers/download.rs
- orb-blob/src/program.rs
- orb-blob/tests/e2e_node_share.rs
all clients now subscribe and manage listening to the topic with a task.
> fix(blobs): create inner task for listening

- orb-blob/p2p/src/lib.rs
- orb-blob/p2p/tests/two_peers_1_bootstrap.rs
- orb-blob/src/handlers/download.rs
- orb-blob/src/program.rs
> docs(blobs): rename Client to PeerTracker and add example

- nix/machines/nixos-common.nix
> chore(hil): added ryan-wld-asahi ssh key to hil

- jobs-agent/tests/check_my_orb.rs
- jobs-agent/tests/common/fake_orb.rs
- jobs-agent/tests/common/fixture.rs
- jobs-agent/tests/job_handler.rs
- jobs-agent/tests/orb_details.rs
- jobs-agent/tests/read_file.rs
- jobs-agent/tests/reboot.rs
temporary fix to reduce flakyness of tests, actual fix incoming soon tm
> test(jobs-agent): temp fix to reduce flakyness

- .github/workflows/rust-ci.yaml
we were previously getting HTTP 400 errors from the rust cache.
> fix(ci): update rust cache

- .github/workflows/release.yaml
adds orb-jobs-agent to automated release pipeline
> chore: add orb-jobs-agent to automated release pipeline

- Cargo.lock
- Cargo.toml
- hil/src/boot.rs
- hil/src/ftdi.rs
NOTE: Vibe coded with codex + gpt-5
> chore(hil): bump nusb to 0.2.0

- flake.nix
- nix/shells/flake-outputs.nix
- nix/shells/nfsboot.nix
- nix/shells/tegra-bash.nix
a bit awkward that the script and the dependencies are managed in two separate repos. Oh well.
> feat(hil): add devshell for nfsbootcmd.sh

- hil/src/commands/nfsboot.rs
put thing most egregiously wrong first
> chore(hil): reorder nfsboot env checks for slightly better ux

- hil/src/commands/flash.rs
- hil/src/commands/nfsboot.rs
- hil/src/main.rs
- hil/src/nfsboot.rs
- hil/src/rts.rs
mostly a refactor, but also extracts the RTS
> feat(hil): nfsboot unzip rts

- backend-status/dbus/Cargo.toml
- backend-status/dbus/src/lib.rs
- backend-status/dbus/src/types.rs
- backend-status/src/dbus/intf_impl.rs
- location/src/dbus.rs
adds `LteInfo` struct and corresponding dbus method to receive the info
> feat(backend-status): lte_info

- hil/src/nfsboot.rs
- hil/src/rts.rs
Now the nfsboot subcommand actually triggers the nfsbootcmd.sh
> feat(hil): nfsboot command calls nfsbootcmd.sh

- .github/workflows/release.yaml
- Cargo.lock
- connd/Cargo.toml
- connd/debian/worldcoin-connd.service
- connd/src/backend_status_reporter.rs
- connd/src/dd_reporter.rs
- connd/src/lib.rs
- connd/src/main.rs
- connd/src/modem_monitor.rs
- connd/src/utils.rs
- service file for `orb-connd`
- cargo deb for `orb-connd`
- handle sigint and sigterm
- add `orb-telemetry`
- use `task::spawn_blocking` in a more granular manner in `dd_reporter` to allow aborting tasks
- improve logging
> chore(connd): cargo deb + systemd service + handle singit / sigterm

- backend-status/dbus/src/types.rs
- backend-status/src/backend/status.rs
- backend-status/src/backend/types.rs
- `CellularStatusApiV2`  struct
- sending `CellularStatusApiV2` to backend
> feat(backend-status): cellular status

- hil/src/nfsboot.rs
When running nfsboot, we extract the rts. Therefore the actual path being mounted is ephemeral / is not known by the person setting the CLI flags.
This pr special cases a `--mount whatever,/rtsdir` to remap `rtsdir` to the path to the extracted rts directory.
> feat(hil): add special case for mounting rts

- Cargo.lock
- hil/Cargo.toml
- hil/src/commands/flash.rs
> fix(hil)!: made cli defaults more amenable to average devs

- hil/src/nfsboot.rs
> chore(hil): added more debug statements to help troubleshooting

- Cargo.lock
- qr-link/Cargo.toml
* bump version to match latest orb relay message
> chore: Bump orb relay message version

- Cargo.lock
- qr-link/Cargo.toml
> chore: bump relay messsage version

- mcu-util/src/orb/security_board.rs
Fixes ORBS-1038
Just a mirror of https://github.com/worldcoin/orb-software/pull/706
> fix(mcu-util): sec.mcu image switch

- xtask/src/cmd/deploy.rs
- use cargo.toml metadata for systemd service names
> fix(xtask/deploy): use cargo metadata for systemd svc names
